[package]
name = "snoo"
version = "0.1.0"
authors = ["Seth Lopez <seth@sethlopez.me>"]

[dependencies]
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.5"
tokio-core = "0.1"